const ROLES = Object.freeze({
  COMMUNITY_MEMBER: 'COMMUNITY_MEMBER',
  RANGER: 'RANGER',
  COMMUNITY_LIAISON_OFFICER: 'COMMUNITY_LIAISON_OFFICER',
  PARK_MANAGER: 'PARK_MANAGER',
  RANGER_SUPERVISOR: 'RANGER_SUPERVISOR',
  RESEARCHER: 'RESEARCHER',
  ADMIN: 'ADMIN',
});

const ROLE_VALUES = Object.freeze(
  Object.values(ROLES)
);

module.exports = {
  ROLES,
  ROLE_VALUES,
};