const mongoose = require('mongoose');

const conflictReportSchema = new mongoose.Schema(
  {
    /*
     * Community member who submitted the report.
     * For SMS reports this can be null if the sender
     * does not have a registered application account.
     */
    reporter: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },

    /*
     * Optional ID generated by the mobile application.
     * Useful later when syncing reports created offline.
     */
    clientReportId: {
      type: String,
      trim: true,
      unique: true,
      sparse: true,
    },

    /*
     * Main conflict category.
     *
     * The case study specifically identifies
     * elephant sightings and crop-raiding.
     * OTHER keeps the design flexible.
     */
    conflictType: {
      type: String,
      enum: [
        'ELEPHANT_SIGHTING',
        'CROP_RAIDING',
        'OTHER',
      ],
      required: [
        true,
        'Conflict type is required',
      ],
    },

    /*
     * Community member's description of the event.
     */
    description: {
      type: String,
      required: [
        true,
        'Conflict description is required',
      ],
      trim: true,
      minlength: [
        5,
        'Description must contain at least 5 characters',
      ],
      maxlength: [
        1500,
        'Description cannot exceed 1500 characters',
      ],
    },

    /*
     * How the report was received.
     */
    reportingChannel: {
      type: String,
      enum: [
        'MOBILE_APP',
        'SMS',
      ],
      default: 'MOBILE_APP',
      required: true,
    },

    /*
     * Conflict location.
     *
     * GPS:
     *   latitude + longitude required.
     *
     * MANUAL:
     *   user can provide coordinates or a
     *   manual location description.
     */
    location: {
      source: {
        type: String,
        enum: [
          'GPS',
          'MANUAL',
        ],
        required: [
          true,
          'Location source is required',
        ],
      },

      latitude: {
        type: Number,
        min: [
          -90,
          'Latitude must be between -90 and 90',
        ],
        max: [
          90,
          'Latitude must be between -90 and 90',
        ],
      },

      longitude: {
        type: Number,
        min: [
          -180,
          'Longitude must be between -180 and 180',
        ],
        max: [
          180,
          'Longitude must be between -180 and 180',
        ],
      },

      manualLocation: {
        type: String,
        trim: true,
        maxlength: [
          300,
          'Manual location cannot exceed 300 characters',
        ],
      },
    },

    /*
     * Optional evidence uploaded to Cloudinary.
     *
     * Multiple images are allowed so the model also
     * supports 0..* supporting evidence.
     */
    evidence: [
      {
        url: {
          type: String,
          required: true,
          trim: true,
        },

        publicId: {
          type: String,
          required: true,
          trim: true,
        },

        originalName: {
          type: String,
          trim: true,
        },

        uploadedAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],

    /*
     * Current report status.
     *
     * Invalid reports are not saved as submitted
     * reports. Validation happens before creation.
     */
    status: {
      type: String,
      enum: [
        'SUBMITTED',
        'UNDER_REVIEW',
        'RESPONDING',
        'RESOLVED',
      ],
      default: 'SUBMITTED',
    },

    /*
     * Urgency can later be updated by an
     * authorized Ranger or Liaison Officer.
     */
    urgencyLevel: {
      type: String,
      enum: [
        'LOW',
        'MEDIUM',
        'HIGH',
        'CRITICAL',
      ],
      default: 'MEDIUM',
    },

    /*
     * Duplicate detection information.
     *
     * Important:
     * Potential duplicate reports are NOT deleted
     * or rejected.
     */
    duplicateInfo: {
      isPotentialDuplicate: {
        type: Boolean,
        default: false,
      },

      duplicateOf: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'ConflictReport',
        default: null,
      },
    },

    /*
     * Ranger or Community Liaison Officer
     * currently handling the report.
     */
    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },

    /*
     * Basic response information.
     */
    response: {
      note: {
        type: String,
        trim: true,
        maxlength: [
          1500,
          'Response note cannot exceed 1500 characters',
        ],
      },

      respondedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        default: null,
      },

      respondedAt: {
        type: Date,
        default: null,
      },
    },
  },
  {
    timestamps: true,

    toJSON: {
      virtuals: true,
    },

    toObject: {
      virtuals: true,
    },
  }
);

/*
 * Location validation
 *
 * GPS reports must contain coordinates.
 *
 * Manual reports must contain either coordinates
 * or a manual location description.
 */
conflictReportSchema.pre(
  'validate',
  function (next) {
    if (!this.location) {
      return next(
        new Error(
          'Conflict location is required'
        )
      );
    }

    const {
      source,
      latitude,
      longitude,
      manualLocation,
    } = this.location;

    const hasCoordinates =
      latitude !== undefined &&
      latitude !== null &&
      longitude !== undefined &&
      longitude !== null;

    if (
      source === 'GPS' &&
      !hasCoordinates
    ) {
      return next(
        new Error(
          'Latitude and longitude are required for GPS location'
        )
      );
    }

    if (
      source === 'MANUAL' &&
      !hasCoordinates &&
      !manualLocation?.trim()
    ) {
      return next(
        new Error(
          'Manual location or coordinates are required'
        )
      );
    }

    next();
  }
);

/*
 * Common database indexes.
 */
conflictReportSchema.index({
  reporter: 1,
  createdAt: -1,
});

conflictReportSchema.index({
  status: 1,
  createdAt: -1,
});

conflictReportSchema.index({
  conflictType: 1,
  createdAt: -1,
});

const ConflictReport =
  mongoose.models.ConflictReport ||
  mongoose.model(
    'ConflictReport',
    conflictReportSchema
  );

module.exports = ConflictReport;